### ISSUE TITLE
.tdb file help me please

### ISSUE THREAD

**Issue by EvilUltralisco** [Erik-JS/SSSS_Tools#1]
Hi Erik JS, you're probably the only person who understands more about this and can probably help me. I downloaded your TDBMaker to edit .tdb files, but from another game, which is called Serious Sam Next Encounter, released for Xbox and PS2 in 2004. The idea was to modify the .tdb files to translate the game texts into other languages. However, TDBMaker gives me an error when trying to convert them. Do you have any idea what might be going on? or do you know any other way to edit these .tdb? I've been trying to open them for over 2 years and I've never found a way. It would be a great help if I could send them to you for analysis. Thank you very much in advance

PS: When I open these .tdb with Notepad++ I can see the texts and edit them, but when I put them back into the game the words are moved from their place.

**Comment by Erik-JS** [comment]
TDBMaker expects the .tdb file to be in a certain format. If the .tdb file isn't from Saint Seiya Brave Soldiers or Soldiers Soul, it most likely will be in another format. Someone needs to analyze the file and figure out its format.

You can send me the files, or I can just grab the game off somewhere. Can't promise anything but I'll see what I can do. I'm keeping this issue open for now so we can keep chatting through here, no problem. I don't know if you have Discord, but if you want you can call me there (`Erik JS#4962`).

**Comment by EvilUltralisco** [comment]
Thank you very much! I sent you a friend request to Discord. My name there is Evil_Ultralisco#9045

**Comment by Erik-JS** [comment]
Closing issue now. Repository for TDB files from SSNE is already online.

https://github.com/Erik-JS/SeriousTDB
